name: Build Alist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
    steps:

      - name: Pull xhofe/alist & xhofe/alist-aria2 
        run: |
             docker pull xhofe/alist:latest; docker pull xhofe/alist-aria2:latest
             docker tag xhofe/alist:latest boxinaclosedbox/alist:latest
             docker tag xhofe/alist:latest ghcr.io/boxinaclosedbox/alist:latest
             docker tag xhofe/alist-aria2:latest boxinaclosedbox/alist:latest-aria2
             docker tag xhofe/alist-aria2:latest ghcr.io/boxinaclosedbox/alist:latest-aria2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Push Images
        run: |
             docker push boxinaclosedbox/alist:latest
             docker push ghcr.io/boxinaclosedbox/alist:latest
             docker push boxinaclosedbox/alist:latest-aria2
             docker push ghcr.io/boxinaclosedbox/alist:latest-aria2
             docker logout

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_2 }}
          password: ${{ secrets.DOCKERHUB_TOKEN_2 }}

      - name: Push to alternate account
        run: |
             docker tag xhofe/alist:latest ${{ secrets.DOCKERHUB_USERNAME_2 }}/${{ secrets.NEW_IMAGE_NAME }}:latest
             docker tag xhofe/alist-aria2:latest ${{ secrets.DOCKERHUB_USERNAME_2 }}/${{ secrets.NEW_IMAGE_NAME }}:latest-aria2
             docker push ${{ secrets.DOCKERHUB_USERNAME_2 }}/${{ secrets.NEW_IMAGE_NAME }}:latest
             docker push ${{ secrets.DOCKERHUB_USERNAME_2 }}/${{ secrets.NEW_IMAGE_NAME }}:latest-aria2